# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
email: georiviere@parc-haut-jura.fr
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://georiviere.fr" # the base hostname & protocol for your site
analytics: UA-40919875-1
 
excerpt_separator: <!--more-->

translate_meta:
  fr:
    title: GeoRivière, un outil pour suivre et gérer les cours d'eau
    description: Suite logicielle webmapping composée d’un outil métier SIG
    keywords: GeoRivière, SIG, logiciel gestion des cours d'eau, GEMAPI

# Build settings
markdown: kramdown
future: true
sass:
    sass_dir: assets/css/
    style: :nested

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll
    values:
      layout: "post"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts-en" # previously `post` in Jekyll
    values:
      layout: "post-en"

translate_menu:
  fr:
    home:
      name: "Accueil"
      url: "index.html"
    application:
      name: "Application"
      url: "application.html"
    apropos:
      name: "À propos"
      url: "apropos.html"
    ressources:
      name: "Ressources"
      url: "ressources.html"
    contact:
      name: "Contact"
      url: "contact.html"
